// app/layout.jsx
import { GeistSans, GeistMono } from 'geist/font';
import "./globals.css";
import { Providers } from './Providers';
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import ChatButton from "@/Components/Chat/ChatButton";

export const metadata = {
  title: "M Collection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="relative">
        <Providers>
          <Header />
          <main className="min-h-screen mt-20">{children}</main>
          <Footer />
          <ChatButton />
        </Providers>
      </body>
    </html>
  );
}